version: '3.7'
services:
  sso-java-client:
    #image: sso-java-client:latest
    network_mode: host
    ports:
      - "8080:8080"
    environment:
      - CLIENT_ID=YOUR_CLIENT_ID
      - CLIENT_SECRET=YOUR_CLIENT_SECRET
      - SSO_ISSUER=https://demo-accounts-api.tapsi.ir/api/v1/sso-user/oidc
      - SSO_JWK_URI=https://demo-accounts-api.tapsi.ir/api/v1/sso-user/keys
      - AUTH_REDIRECT_URI=http://localhost:3000/
    build:
      context: ./
